### ISSUE TITLE
characterization fails on fits 0.8.4

### ISSUE THREAD

**Issue by acozine** [projecthydra/sufia#1283] opened 2015-08-18 14:18 UTC
On a vanilla Sufia installation with fits 0.8.4, characterization of jpg files fails with the message
```
Cannot insert nodes into the document because it is empty. Try defining self.xml_template on the FitsDatastream class
```
After reverting to fits 0.6.0, characterization jobs succeed.

**Comment by awead** [comment] 2015-08-18 14:25
This is an outstanding issue because the xml output from Fits changed between 0.6 and 0.8.4. The issue is that the OM terminology needs to be rewritten to account for the new xml output. I believe @mjgiarlo did some work on this, but I'm not sure where it stands. At present, the solution is to use Fits 0.6 only.

**Comment by jcoyne** [comment] 2015-08-18 14:27
@awead This should probably be documented in the dependencies section of the readme

**Comment by awead** [comment] 2015-08-18 14:32
@jcoyne done.

**Comment by hackmastera** [comment] 2015-08-19 13:57
I've been using 0.8.4 and never seen this issue. Somewhat disconcerting. How can I reproduce?

**Comment by mjgiarlo** [comment] 2015-08-19 22:04
@hackmastera I suspect this is because FITS is a loose wrapper around other tools, and different kinds of files produce different output. That'd explain why some see it in some environments and others don't. This is also part of the reason I'd like to move beyond FITS, tbh.

**Comment by mark-dce** [comment] 2015-12-01 21:13
To clarify, is this an issue with all versions of Sufia or just 6.x (vs. 7.x)?

I'm seeing it with Sufia 6.3.0, which depends on Sufia-models 6.3.0, which depends on Hydra-derivatives ~>1.0, which I'm guessing assumes FITS 0.6.x format output (vs 0.8.x)

**Comment by grosscol** [comment] 2015-12-01 21:21
@mark-dce this is a 6.x issue.  The Hydra::Works characterization that underpins the 7.x branch was written using the FITS 0.8.4 output.  It also works for the FITS 0.6.x output.  I piped FITS outputs to files in the spec/fixtures directory so that FITS wouldn't have to be invoked to run the tests.  That might help with the making the issues more easily reproduced.
https://github.com/projecthydra-labs/hydra-works/tree/master/spec/fixtures
Although loading the output in the specs is kinda ugly.
https://github.com/projecthydra-labs/hydra-works/blob/master/spec/hydra/works/services/characterization_service_spec.rb#L37-L39

**Comment by mjgiarlo** [comment] 2015-12-14 22:03
With the Sufia 6.x documentation clarified w/r/t its preferred version of FITS, and Sufia 7 using the latest builds of FITS, I am closing this issue. Thanks, all.

**Closed by mjgiarlo** 2015-12-14 22:03 UTC
