### ISSUE TITLE
Edit and view access not persisted when changing permissions from work/edit page

### ISSUE THREAD

**Issue by grosscol** [projecthydra/sufia#1648] opened 2016-03-22 15:57 UTC
### Descriptive summary
Unable to add designee for view/download nor edit access to new or existing work

Sufia 7.x HEAD

What I was looking for in the logs was an update to the `edit_users` or `read_users` being persisted.  These are the snippets of the log results for the checks when viewing a specific work and viewing search results respectively.
```
  Rendered /home/grosscol/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/curation_concerns-0.10.0/app/views/curation_concerns/base/_attributes.html.erb (50.1ms)
[CANCAN] Checking edit permissions for user: demouser@example.com with groups: ["public", "registered"]
[CANCAN] edit_groups: []
[CANCAN] edit_users: ["demouser@example.com"]
[CANCAN] decision: true
```
```
[CANCAN] edit_users: ["demouser@example.com"]
[CANCAN] read_users: ["demouser@example.com"]
```

### Expected behavior
Designating another user with edit or view/download access is persisted.

### Actual behavior
Designating another user with edit or view/download access is *not* persisted.

### Steps to reproduce the behavior
Create two users: bob@example.com & jane@example.com
Log in as jane@example.com
Create new work (and add title)
Select bob@example.com under "Share With" section.
Select edit for "Choose Access"
Press plus button ( a new entry will show up in the Person/Group Access Level table)
Press Save (will be redirected to work's show page)
Click edit this work button or navigate to work's/edit page.
Scroll to bottom to find that the access has not been persisted.

### Related work

Needs to be fixed in order to fully address #1609

**Comment by hectorcorrea** [comment] 2016-04-12 15:04
Reassigning this to @jcoyne as he is already working on https://github.com/projecthydra/sufia/issues/1573

**Comment by jcoyne** [comment] 2016-04-12 15:17
duplicate of #1573

**Closed by jcoyne** 2016-04-12 15:17 UTC
Labels: bug, ready
