### ISSUE TITLE
Template Error in views/curation_concerns/permissions/confirm.html.erb

### ISSUE THREAD

**Issue by coblej** [projecthydra/sufia#1619] opened 2016-03-02 16:29 UTC
### Descriptive summary

Sufia master HEAD
I think there is a typo in https://github.com/projecthydra/sufia/blob/master/app/views/curation_concerns/permissions/confirm.html.erb#L9
I believe the url helper should be `copy_curation_concerns_permission_path` (note `concerns` plural not `concern` singular).

```
Completed 500 Internal Server Error in 67ms

ActionView::Template::Error (undefined method `copy_curation_concern_permission_path' for #<Module:0x007fbdf3f80d78>):
     6:       <%=  I18n.t("sufia.upload.change_permissions_message_html") %>
     7:   </div>
     8:   <div class="form-actions panel-footer">
     9:     <%= button_to "Yes please.", Sufia::Engine.routes.url_helpers.copy_curation_concern_permission_path([sufia,curation_concern]), class: 'btn btn-primary' %>
    10:     <%= link_to "No. I'll update it manually.", curation_concerns_generic_work_path([sufia, curation_concern]), class: 'btn' %>
    11:   </div>
    12: </div>
  /Users/coblej/F4/sufia/app/views/curation_concerns/permissions/confirm.html.erb:9:in `___sers_coblej____sufia_app_views_curation_concerns_permissions_confirm_html_erb___901715167331935300_70226910725080'
  actionview (4.2.0) lib/action_view/template.rb:145:in `block in render'
  activesupport (4.2.0) lib/active_support/notifications.rb:166:in `instrument' 
```

### Expected behavior

Render the page correctly.

### Actual behavior

Throws ActionView::Template::Error.

### Steps to reproduce the behavior

1. In Sufia-based app, on edit Work page, change the Visibility setting and click Save.

### Related work

Link to related tickets or prior related work here.

**Comment by coblej** [comment] 2016-03-02 16:31
I added this issue to the 7.0.0 milestone.  Feel free to remove it from there if that is not appropriate.

**Comment by mjgiarlo** [comment] 2016-03-02 16:56
I believe you're right, @coblej. Thanks!

Refs #1606

**Comment by hectorcorrea** [comment] 2016-03-03 13:21
Closing since this is a duplicate of #1603

**Closed by hectorcorrea** 2016-03-03 13:21 UTC
Labels: bug
