### ISSUE TITLE
Allow User to choose a Thumbnail for a Work

### ISSUE THREAD

**Issue by cam156** [projecthydra/sufia#1073] opened 2015-04-30 12:14 UTC
In the Work show page a user should be able to select a thumbnail for the current Work.

https://wiki.duraspace.org/pages/viewpage.action?pageId=68070466

This is related to #1065, but is an additional work flow not entirely needed for a basic work show page.

**Comment by mjgiarlo** [comment] 2015-12-14 20:49
Duplicate of #1394.

**Closed by mjgiarlo** 2015-12-14 20:49 UTC
Labels: user interface
