### ISSUE TITLE
Move noid state file default location to a better default

### ISSUE THREAD

**Issue by cam156** [projecthydra/sufia#1568] opened 2016-02-11 14:43 UTC
The current location is /tmp, which can be automatically cleaned on system restart.  Move the default to a more secure location would help to keep the state file around.

**Comment by jcoyne** [comment] 2016-02-11 14:57
Duplicate of #1532?

**Comment by mjgiarlo** [comment] 2016-02-17 18:51
Yep, duplicate. Closing!

**Closed by mjgiarlo** 2016-02-17 18:51 UTC
