### ISSUE TITLE
Insert "Add to collection" link/button

### ISSUE THREAD

**Issue by atz** [projecthydra/sufia#1677] opened 2016-03-29 19:14 UTC
When viewing one's own item, especially a newly submitted one, where the page says “Collections: This file is not currently in any collections", insert a button/link to add to a collection.

From a UI/flow point of view, the case of the newly minted object with no collections is the most valuable to catch.  No reason to send the user off searching for a different attack vs. the interface.

**Comment by mjgiarlo** [comment] 2016-03-29 19:37
I'd be interested in soliciting input from folks on the UI WG about this change. @mtribone @elrayle @dt-ucsd @sfbetz @hackmastera @spr7b @newmanld @simosacchi

**Comment by simosacchi** [comment] 2016-03-29 19:46
I think the recommendation from the UI WG was to not display the "Collection" box is the object is not in a collection. To add a work (not a file directly) to a Collection we were proposing to bring a user back to the editing page (which is pretty much the same as the "add new work" one) and let the user establish relationships there. The idea is to streamline the process and not provide too many ways to do the same thing ---so that users get comfortable and confident on where to go to take an action. Please other UI WG folks, jump in if I made any false statement here.

**Comment by newmanld** [comment] 2016-03-29 20:19
I think Simone’s comment reflects our discussion – but now that I look at the Show Pages for a work, I don’t see one global Edit button that takes the owner back to an editing page that has a feature to Add this Work to a Collection.  (See https://wiki.duraspace.org/pages/viewpage.action?pageId=68070436 and https://wiki.duraspace.org/pages/viewpage.action?pageId=68070466 – please comment if I’m not looking at the relevant wireframes.)  Instead I see ‘Edit Permissions”, “Edit Descriptions” and “Add Files”.  So Mike’s suggestion seems to fit on the Work show page.

I don’t see Add to Collection on the Edit Work pages for Descriptions or Permissions – the only place on our wireframes I see to add a work to a Collection is on the Show Page for a Collection (https://wiki.duraspace.org/pages/viewpage.action?pageId=68069887).

So I think without a redesign to our Work Edit pages we need this feature on the Work Show page.  (Unless I’m not up to date on the wireframes I’m looking at…)

**Comment by simosacchi** [comment] 2016-03-29 20:24
This is, afaik, the latest iteration of the proposed wireframes for the work show page (with all variances, including when a logged in user owns the work, towards the end of the page): https://wiki.duraspace.org/display/hydra/Show+Work+%28all+variants%29+-+Phase+1+-+UI+Wireframes

**Comment by newmanld** [comment] 2016-03-29 21:04
Thanks Simone - That explains it and is consistent with our discussion about a single Edit button.  So we must also have an updated Edit Work page that is different than the separate pages I was looking at for Edit Description, edit Permissions etc.?  (I was starting from here: https://wiki.duraspace.org/display/hydra/Sufia+Sprint+UI+Design).

**Comment by simosacchi** [comment] 2016-03-29 21:27
@newmanld you are looking at the wrong wireframes (I know, there are many around taht should be marked as obsolete). 

The correct starting point is this one:https://wiki.duraspace.org/display/hydra/Home+for+user+-+Phase+1+-+UI+Wireframes

See also the following issues where the tabbed UI for creating/editing a work is explained: #1583 #1577 #1573 #1572 #1563 #1562

Please  @mtribone @elrayle @dt-ucsd @sfbetz @hackmastera @spr7b add anything I am missing.

**Comment by mtribone** [comment] 2016-03-29 21:59
@simosacchi You are correct.

@atz In our UI recommendations when creating a new work, people will have the ability to add metadata, files, relationships like collections, etc. so this would catch that critical first step? If you've already or recently created a work and are looking at the show page, we opted for keeping it simple with one, consistent edit button. Otherwise we were putting "edit" links all over the interface for every conceivable piece of info and it really made the interface cluttered.

Take a tour here:
https://wiki.duraspace.org/display/hydra/New+Work+-+Metadata+Tab+-+Phase+1+-+UI+Wireframes#mockup_p1-works-new-step1

**Comment by newmanld** [comment] 2016-03-29 22:00
Thanks @simosacchi<https://github.com/simosacchi>

Let’s get the link on this page -- https://wiki.duraspace.org/display/hydra/Sufia+User+Interface+Working+Group -- to go to this newer starting point instead of the old wireframes to avoid confusion like mine.

I’m in agreement with the single Edit button – glad you directed me to where it exists.

**Comment by jcoyne** [comment] 2016-03-31 17:22
Duplicate of #1708

**Closed by jcoyne** 2016-03-31 17:22 UTC
Labels: enhancement, needs feedback, user interface
