### ISSUE TITLE
Remove superfluous UI buttons on Work Types interface

### ISSUE THREAD

**Issue by vantuyls** [projecthydra/sufia#2931] opened 2016-11-22 17:20 UTC
### Descriptive summary

Work type interface "Close" and "Create Work" buttons are superfluous - those functions are already achieved in the UI, Close can be achieved by clicking outside of the window, Create Work is achieved by selecting the work type you want to create

**Comment by jcoyne** [comment] 2016-11-22 17:24
@vantuyls "Clicking outside the window" may not be an option for someone who is not using a mouse.

**Comment by mtribone** [comment] 2016-11-22 17:31
Additionally, people who use screen readers or other assistive devices have to cycle through options in order to select the option that they would want for their work type. Without the create work button, the options would fire automatically and create a frustrating experience for users.

**Comment by ggeisler** [comment] 2016-11-22 21:32
Also, the design in #2434 did not intend for selecting a work type to trigger the selection. The UI should always indicate which option is currently selected (generic work as the default), but the user has to explicitly choose the Create Work button to actually make the selection.  @hannahfrost created a ticket addressing this a few minutes ago: https://github.com/projecthydra-labs/hyku/issues/496

I also think the Close button has value for all users in clearly showing there is a way to cancel.

**Comment by mjgiarlo** [comment] 2016-12-16 23:09
Sounds like this is a wontfix, caused by an incomplete implementation of the UI for the work type modal. Closing.

**Closed** 2016-12-16 23:09 UTC
Labels: bug
