### ISSUE TITLE
resolve predicate warnings

### ISSUE THREAD

**Issue by jcoyne** [projecthydra/sufia#1693] opened 2016-03-30 15:21 UTC
I'm seeing these warnings in the log:

```
Same predicate (http://purl.org/dc/elements/1.1/creator) used for properties file_author and creator
Same predicate (http://purl.org/dc/elements/1.1/language) used for properties file_language and language
```

we should figure out why this is happening and how to resolve it.

**Comment by hectorcorrea** [comment] 2016-04-05 20:44
More information on this issue. The problem seems to be somewhere in FileSet. 

Class `FileSet` is defined in `.internal_test_app/app/models/file_set.rb` as follows:

```
# Generated by curation_concerns:models:install
class FileSet < ActiveFedora::Base
  include ::CurationConcerns::FileSetBehavior
  include Sufia::FileSetBehavior
end
```

The warning is raised when Ruby processes `include ::CurationConcerns::FileSetBehavior`. I am still digging but wanted to update the ticket in case somebody has any ideas.

**Comment by hectorcorrea** [comment] 2016-04-05 21:18
I think the root of the problem is that module `CurationConcerns::FileSetBehavior` includes `CurationConcerns::BasicMetadata` and `Hydra::Works::Characterization::DocumentSchema` and there is a property on each of these modules that uses the `http://purl.org/dc/elements/1.1/creator` predicate.

This is the line in which `CurationConcerns::BasicMetadata` defines a property that uses the DC:Creator predicate https://github.com/projecthydra-labs/curation_concerns/blob/master/curation_concerns-models/app/models/concerns/curation_concerns/basic_metadata.rb#L18

This is the line in which `Hydra::Works::Characterization::DocumentSchema` defines property that uses the DC:Creator predicate:  https://github.com/projecthydra-labs/hydra-works/blob/master/lib/hydra/works/characterization/schema/document_schema.rb#L4

**Comment by mjgiarlo** [comment] 2016-04-05 22:12
:clap:

**Comment by hectorcorrea** [comment] 2016-04-12 15:25
With https://github.com/projecthydra-labs/curation_concerns/pull/721 now merged this will be fixed once we get the next version of Curation Concerns.

**Comment by mjgiarlo** [comment] 2016-04-12 15:51
:clap: 

Closing.

**Closed by mjgiarlo** 2016-04-12 15:51 UTC
Labels: bug, in progress
