### ISSUE TITLE
My Highlights should not query solr if no trophies are present

### ISSUE THREAD

**Issue by cam156** [projecthydra/sufia#1139] opened 2015-05-12 13:13 UTC
My Highlights does not show highlighted works.

The solr query being sent seems a bit off.  It includes "id:NEVER_USE_THIS_ID"

Full query:

Solr query: get select {"qt"=>"search", "facet.field"=>["resource_type_sim", "creator_sim", "tag_sim", "subject_sim", "language_sim", "based_near_sim", "publisher_sim", "file_format_sim"], "facet.query"=>[], "facet.pivot"=>[], "fq"=>["edit_access_group_ssim:public OR discover_access_group_ssim:public OR read_access_group_ssim:public OR edit_access_group_ssim:registered OR discover_access_group_ssim:registered OR read_access_group_ssim:registered OR edit_access_person_ssim:cam156@psu.edu OR discover_access_person_ssim:cam156@psu.edu OR read_access_person_ssim:cam156@psu.edu", "id:NEVER_USE_THIS_ID"], "hl.fl"=>[], "rows"=>10, "facet"=>true, "f.resource_type_sim.facet.limit"=>6, "f.creator_sim.facet.limit"=>6, "f.tag_sim.facet.limit"=>6, "f.subject_sim.facet.limit"=>6, "f.language_sim.facet.limit"=>6, "f.based_near_sim.facet.limit"=>6, "f.publisher_sim.facet.limit"=>6, "f.file_format_sim.facet.limit"=>6, "sort"=>"score desc, date_uploaded_dtsi desc"}

**Comment by cam156** [comment] 2015-05-12 13:20
After a bit more digging we are querying solr even if there are no trophies for the user.  We should only contact solr if there is a possibility there are documents present.

**Comment by mjgiarlo** [comment] 2015-12-16 22:01
Related to #1140.

**Comment by njaffer** [comment] 2016-01-14 20:09
@cam156 , I can highlight the work in Sufia 7.0.0 master branch, not sure where should I be looking for the trophies you mentioned

**Comment by hectorcorrea** [comment] 2016-01-14 20:29
@njaffer You can see the user's highlighted works (aka trophies) by going to your user profile page (go to http://localhost:3000/dashboard and click "View Profile") Your highlighted works will be shown in the "Highlighted" tab.

**Comment by njaffer** [comment] 2016-01-14 20:52
Thank you @hectorcorrea for sharing the screenshot!

**Comment by hectorcorrea** [comment] 2016-01-27 21:45
I cannot reproduce this error in Sufia 7.

The code to display trophies only fetches from Solr if the user has trophies (see https://github.com/projecthydra/sufia/blob/master/app/models/concerns/sufia/user.rb#L116) 

```
trophies.map do |t|
  begin
    ::GenericWork.load_instance_from_solr(t.generic_work_id)
  rescue ActiveFedora::ObjectNotFoundError
    logger.error("Invalid trophy for user #{user_key} (generic work id #{t.generic_work_id})")
    nil
  end
end.compact
```

Even when the user has trophies I could not find a call to Solr with the `id:NEVER_USE_THIS_ID` bit. 

I would vote to close this ticket. @cam156 ???

**Comment by hectorcorrea** [comment] 2016-01-27 22:16
Nevermind...I see the error that @cam156 reported. I was looking at Highlights under the user profile. not at "My Highlights" on the dashboard. This ticket still is relevant.

**Closed** 2016-02-01 16:33 UTC
Labels: bug, in progress
