### ISSUE TITLE
Analytics button link does not respect relative_url_root

### ISSUE THREAD

**Issue by grosscol** [projecthydra/sufia#2105] opened 2016-05-31 17:39 UTC
### Descriptive summary

Sufia 7.0.0.rc
When deploying a Sufia based application at url that isn't '/' and analytics is enabled, the analytics buttons rendered on the work and file set pages have the incorrect url.  The relative_url_root is not included.
### Expected behavior

Analytics button url to be of the form `/<relative_url_root>/works/<id>/stats`
### Actual behavior

Analytics button url is of the form `/works/<id>/stats`
### Steps to reproduce the behavior
1. Generate .internal_test_app
2. Add `config.relative_url_root = '/myapp'` to `.internal_test_app/config/application.rb`
3. Set `config.analytics = true` in `.internal_test_app/config/initializers/sufia.rb`
4. Run rails server for internal_test_app
5. Create a work.
6. View that work.
7. See href attribute of Analytics Button
### Related work

This Rails issue https://github.com/rails/rails/issues/20920, might come up in a google search, but it's a red herring.

Likely, resolution is to use polymorphic_path instead of having the presenter call an engine helper to generate the url.

**Comment by grosscol** [comment] 2016-05-31 17:50
Links are generated in these two partials:
sufia/app/views/curation_concerns/base/_show_actions.html.erb
sufia/app/views/curation_concerns/file_sets/_show_actions.html.erb

Not sure if `stats_polymorphic_path[main_app, curation_concern]` would be apropos in the base _show_actions, but that's where my first stab would be.

**Comment by mjgiarlo** [comment] 2016-08-12 21:25
@grosscol I closed #2379 as a duplicate of this (more detailed) ticket. I saw you were assigned to that ticket. Are you actively working on this issue? If so, I've gone ahead and assigned you to this issue too.

**Closed** 2016-12-21 23:42 UTC
Labels: bug, MOVE TO HYRAX!
