### ISSUE TITLE
Analytics button does not respect relative_url_root

### ISSUE THREAD

**Issue by grosscol** [projecthydra/sufia#2379] opened 2016-07-28 13:32 UTC
### Descriptive summary
The analytics button on the show pages does not render a link that respects relative_url_root.

### Expected behavior
The button renderer to create a link to 

`myhost.edu/rel_root/mywork/id/stats`
### Actual behavior
The button renderer creates a link to:
`myhost.edu/mywork/id/stats`

### Steps to reproduce the behavior

1. Generate app
1. Set config.analytics=true in sufia initializer
2. Create a work
3. View work

**Comment by mjgiarlo** [comment] 2016-08-12 21:24
Duplicate of #2105. Closing.

**Closed by mjgiarlo** 2016-08-12 21:24 UTC
Labels: bug, ready
