### ISSUE TITLE
Deposit to Admin set with review workflow gives error, submits, then publishes without review

### ISSUE THREAD

**Issue by julesies** [projecthydra/sufia#3110] opened 2017-02-23 20:43 UTC
7.3.0rc1 (upgraded from 7.2) test system. I have a feeling we could be experiences config issues mixed with bug(s). We did follow directions here https://github.com/projecthydra/sufia/wiki/Mediated-Deposit-Workflow . This is long...please let me know if I can provide anything else or clarify. @vantuyls 

I set up an admin set with a 1 step workflow (the one that comes baked in). I added depositors and managers to the admin set under participants. I also assigned the corresponding workflow roles to the same users. Then as the depositor, I create the work, select the correct admin set and get error "we're sorry, but something went wrong" see below. 
![screen shot 2017-02-22 at 4 15 06 pm](https://cloud.githubusercontent.com/assets/4356335/23277292/496a2dc0-f9db-11e6-8650-cd20a5e7d0a1.png)
stack trace...
[Julie_s_Error.txt](https://github.com/projecthydra/sufia/files/797632/Julie_s_Error.txt)

However, the work _did_ submit without files _and_ the work record is available to logged out viewers in "pending_review" status as seen under the title. 
![screen shot 2017-02-23 at 3 14 31 pm](https://cloud.githubusercontent.com/assets/4356335/23277406/bdb50c18-f9db-11e6-9328-d5763b395a7f.png)

When I log in as the "manager/reviewer" I do not see any notifications for review and I can't see the admin tab.

however, when logged in as the manager/reviewer, I can navigate to the work directly. Then I can see  an option at the bottom of the page "Review and Approval". When I try to approve, I get an error "We're sorry, but something went wrong". 

However, the work status _changes_ on the work view to _complete_. see below. 
![screen shot 2017-02-23 at 3 31 54 pm](https://cloud.githubusercontent.com/assets/4356335/23277798/3d33d75c-f9dd-11e6-8464-00f73271b217.png)

When logged in as an admin, I can access the workflow:review tab, but it's empty. I can also see the Review and Approval option at the bottom when I navigate to the work directly.

**Comment by julesies** [comment] 2017-02-23 20:45
@scholarworks

**Comment by julesies** [comment] 2017-02-23 21:11
In further testing with newly created admin sets without review workflows, I see similar behavior. I create a work, submit it, get the error, yet the work is created and found within the admin set without a file attached.

**Comment by mjgiarlo** [comment] 2017-02-27 19:44
@jcoyne @scholarworks @jeremyf @randalldfloyd Do y'all have any ideas as to why this might be happening?

**Comment by mjgiarlo** [comment] 2017-02-27 20:34
@julesies OK, I'd like to see if I can reproduce this. If I spin up a 7.3.0.rc1 instance that was upgraded from 7.2.0, I should be able to reproduce this bug via... creating an admin set and depositing into it as a non-administrative user, regardless of the workflow assigned to said admin set? Let me know what you think is the simplest way to reproduce this and I'll give it a whirl.

The file attachment part is weird, and makes me wonder how much of the behavior you're seeing might be caused by background workers not running as expected. Do the attached files *never* show up?

**Comment by jcoyne** [comment] 2017-02-27 20:34
The first error will be fixed by backporting this (https://github.com/projecthydra/curation_concerns/commit/987f36faabcd660a958fa0360e7c5e1ac0b23bae) to the 1-7-stable branch of CC and cutting a release.

**Comment by julesies** [comment] 2017-02-27 20:43
@mjgiarlo right. the admin set should have the 1 step workflow. The depositor had a non-admin role and the reviewer also had a non-admin role (given depositor and manager in the admin set & given roles in the workflow tab). Since I can deposit files successfully in the Default Admin set, I assumed it wasn't background workers. pinging @lfarrell for those types of questions 😸 .

**Comment by julesies** [comment] 2017-02-27 21:15
Oh I see what you are asking. Yes I'm getting the weirdness on both workflowed and nonworkflowed admin sets at this point. I've been changing settings a lot and have 5 admin sets set up with diff scenarios.

**Comment by mjgiarlo** [comment] 2017-02-27 21:55
@julesies OK. I'm inclined to pursue the fix @jcoyne recommends above and cut a new CC release, and then I can update Sufia and see if I can't reproduce this.

**Comment by julesies** [comment] 2017-02-27 22:41
Sounds good!

**Comment by mjgiarlo** [comment] 2017-03-02 00:11
This should be fixed by https://github.com/projecthydra/sufia/pull/3118. Closing for now. We should run a similar test when we cut 7.3.0.rc2 to confirm. Thanks!

**Closed by mjgiarlo** 2017-03-02 00:11 UTC
Labels: bug, collections/admin sets, mediated deposit, needs feedback
