### ISSUE TITLE
Proxy user cannot deposit a file or work

### ISSUE THREAD

**Issue by njaffer** [projecthydra/sufia#1609] opened 2016-02-29 02:28 UTC
### Descriptive summary

In Sufia 7, when I try to upload a work as a proxy, the error says : Model mismatch

### Expected behavior
Don't show the on behalf of option in upload work  OR make it work!

### Actual behavior
The 'on behalf of option' is displayed in upload a work, and does not work. Here is the traceback:
```
ActiveFedora::ActiveFedoraError - Model mismatch. Expected GenericWork. Got: FileSet:
  active-fedora (9.9.0) lib/active_fedora/relation/finder_methods.rb:199:in `class_to_load'
  active-fedora (9.9.0) lib/active_fedora/relation/finder_methods.rb:189:in `load_from_fedora'
  active-fedora (9.9.0) lib/active_fedora/relation/finder_methods.rb:175:in `find_one'
  active-fedora (9.9.0) lib/active_fedora/relation/finder_methods.rb:234:in `find_with_ids'
  active-fedora (9.9.0) lib/active_fedora/relation/finder_methods.rb:58:in `find'
  active-fedora (9.9.0) lib/active_fedora/querying.rb:3:in `find'
  /Users/njaffer/sufia/app/services/sufia/change_content_depositor_service.rb:4:in `call'
  /Users/njaffer/sufia/app/jobs/content_depositor_change_event_job.rb:34:in `work'
  /Users/njaffer/sufia/app/jobs/content_depositor_change_event_job.rb:45:in `proxy_depositor'
  /Users/njaffer/sufia/app/jobs/content_depositor_change_event_job.rb:40:in `log_user_event'
  /Users/njaffer/sufia/app/jobs/event_job.rb:23:in `perform'
  /Users/njaffer/sufia/app/jobs/content_event_job.rb:10:in `perform'
  /Users/njaffer/sufia/app/jobs/content_depositor_change_event_job.rb:20:in `perform'
```

### Steps to reproduce the behavior

1. Assign user B as a proxy user
1. Login as user B and upload a work

### Related work

Link to related tickets or prior related work here.

**Comment by jcoyne** [comment] 2016-02-29 04:48
@mjgiarlo Is this correct? 

> Don't show the on behalf of option in upload work 

I thought we would want to keep that behavior.

**Comment by njaffer** [comment] 2016-02-29 13:55
@jcoyne , I worked on the proxy user before as well and I remember it was working, but something has changed and I cannot deposit a file or work. Looking for more clues....

**Comment by mjgiarlo** [comment] 2016-03-01 17:17
Yes, we should keep the on-behalf-of option for uploading works, @jcoyne.

**Comment by njaffer** [comment] 2016-03-03 18:25
@jcoyne: When I upload a work on behalf of a proxy user, to my knowledge, the error is generated on this line: 
https://github.com/projecthydra-labs/curation_concerns/blob/master/app/controllers/concerns/curation_concerns/file_sets_controller_behavior.rb#L51

**Comment by njaffer** [comment] 2016-03-11 21:07
@mjgiarlo, @jcoyne: The change_content_depositor is called when a proxy user deposits a work or fileset, and hence it fails on this line:

https://github.com/projecthydra/sufia/blob/81bd825499f559ff15449f8fff32440bc8068b8b/app/services/sufia/change_content_depositor_service.rb#L4

any thoughts?

**Comment by mjgiarlo** [comment] 2016-03-11 21:16
I suspect this is related to the decision to merge #1551 before we had fully figured out what it would mean to support proxies/transfers at both the FileSet and GenericWork level in the codebase. For now, if we're going to continue supporting proxies/transfers of FileSets -- an idea which I don't love but I'm loath to suggest ripping that out! -- it sounds like we'll need this service to know how to deal with both FileSets and GenericWorks.

How are we currently handling proxies/transfers of FileSets? Are empty GenericWorks created to contain them, or are they sitting out there without a container?

Pinging @jcoyne @cam156 @awead @hectorcorrea @grosscol so they can see this and sound off on it as well.

**Comment by jcoyne** [comment] 2016-03-11 21:30
I don't think we should allow transferring FileSets. I'd suggest we rip that out and only works should be transferable.

**Comment by njaffer** [comment] 2016-03-11 21:34
@mjgiarlo: Yeah I agree it is related to the ticket you mentioned, So the question is what are the use cases for proxy deposits, is there a case for proxy deposit of work and files both?

@grosscol: In our case we will need the proxy deposit of the file-set only?

**Comment by mjgiarlo** [comment] 2016-03-11 21:52
I agree with you, @jcoyne.

Right now, I don't think there's any use case to allow proxy deposit of files.

**Comment by awead** [comment] 2016-03-12 14:06
I agree as well. In our Scholarsphere application, we wouldn't need to transfer FileSets, only Works.

**Comment by grosscol** [comment] 2016-03-22 15:33
There are two use cases that come to mind:
1) Creating a work on behalf of another user and uploading files to it.
2) Uploading files to an existing work on behalf of the user that owns the work.

The first should be straight forward create the work with the depositor and the owner being different.  This covers depositing digitized content on behalf of the curator or archivist.

The second would be for aggregating the work of multiple users working under another.  I think this may be covered by the can_edit, but it's not currently working

**Comment by mjgiarlo** [comment] 2016-03-22 18:08
Are you still working on this ticket, @njaffer, or is it available for someone else to pick up?

**Comment by njaffer** [comment] 2016-03-22 18:49
@mjgiarlo: I have added this topic for HDC. I have worked on it so I can continue once the expectation of the proxy user behavior is clarified.

**Comment by mjgiarlo** [comment] 2016-03-23 18:42
Thanks, @njaffer!

**Comment by elrayle** [comment] 2016-03-24 17:53
#### Sufia 6 behavior of proxy:
* User A_Author sets User P_Proxy as one of their proxy users on the dashboard page
* User P_Proxy batch uploads file doc.pdf after selecting On Behalf of A_Author
  * enter metadata for doc.pdf and save  _NOTE: Creator is set to P_Proxy.  I would have expected it to be set to A_Author._
  * under the covers - adds user activity of P_Proxy deposited doc.pdf
  * under the covers - adds user activity of P_Proxy transfered ownership of doc.pdf to A_Author
  * under the covers - adds user activity of P_Proxy edited doc.pdf  (not sure what change was made)
  * under the covers - changes File metadata for field Depositor to A_Author.  I would have expected this to remain P_Proxy since this is the actual person who made the deposit.
  * under the covers - give P_Proxy edit permissions for doc.pdf which is now owned by A_Author  _NOTE: A_Author can revoke edit permissions for P_Proxy by editing doc.pdf and deleting the edit permissions._

#### Unexpected behaviors for Sufia 6 that we propose to change in Sufia 7
* After the above process is complete...
  * the value for Creator is set to P_Proxy by default.  It should be set to A_Author by default.
  * the value for Depositor is set to A_Author.  Since P_Proxy made the actual deposit, P_Proxy should be the value for Depositor.

*Observation:*  In the fedora object for doc.pdf, the field on_behalf_of is set to A_Author and the field  proxyDepositor is set to P_Proxy, as expected for both.  Neither appear to be displayed via the UI.

#### Other Sufia 7 observations

The proxy process is controlled by the Work instead of the Fileset, but having the proxyDepositor and on_behalf_of fields set on the work and all its filesets seems reasonable so each part has clear provenance.

**Closed** 2016-03-29 16:55 UTC
Labels: bug, in progress
