### ISSUE TITLE
Plan for how are we going to do analytics for works

### ISSUE THREAD

**Issue by cam156** [projecthydra/sufia#1012] opened 2015-03-26 21:16 UTC
Would the analytics combine the views of the files and the work
would it just be related to the work
would the user stats on the dashboard be at the file or works or both

**Comment by cam156** [comment] 2015-03-27 18:12
@mjgiarlo and I discussed this last night.  For the first blush we will continue with our current analytics. A later release could include analytics at the work level.

It would be good if we could add view analytics at the work level, but there is no intention of offering a work download in this phase.

**Comment by mjgiarlo** [comment] 2015-12-14 20:52
Duplicate of #1455. Closing.

**Closed by mjgiarlo** 2015-12-14 20:52 UTC
Labels: ready
