### ISSUE TITLE
Multiple work types: Need unique titles on different work creation forms.

### ISSUE THREAD

**Issue by hackmastera** [projecthydra/sufia#2435] opened 2016-08-09 19:58 UTC
### Descriptive summary

On each 'new work' page there is no indication of what kind of work you're creating.

### Expected behavior
Headings should be, e.g. 'Create new Work' and 'Create new Snowflake'.

### Actual behavior
Heading is 'Create new Work' regardless of work type

### Steps to reproduce the behavior

1. Generate a 2nd curation concern using the sufia:work generator
1. choose 'works > new work' on top bar

### Related work

umbrella ticket is #2199

**Comment by mjgiarlo** [comment] 2016-08-09 20:38
From @jcoyne on #2411
> The text isn't changing because the existing translation for that button:
https://github.com/projecthydra/sufia/blob/master/config/locales/sufia.en.yml#L104
> 
> Doesn't make use of the work_type variable that is passed in:
https://github.com/projecthydra/sufia/blob/master/app/views/dashboard/_index_partials/_heading_actions.html.erb#L12
> 
> Perhaps it should be `create_work: Create ${work_type}`?

**Comment by jcoyne** [comment] 2016-08-31 12:33
Not a bug. This is a new feature.

**Comment by jcoyne** [comment] 2016-10-28 16:50
I think this is now fixed.

**Closed by jcoyne** 2016-10-28 16:50 UTC
Labels: enhancement, user interface
